### ISSUE TITLE
Is there any function that can deauthorize? , seems like there is no deauthorize function on new released version

### ISSUE THREAD

**Issue by StevenStarz** [SweetzpotAS/StravaZpot-Android#16]
@truizlop

**Comment by StevenStarz** [comment]
AuthenticationConfig config = AuthenticationConfig.create()
                            .debug()
                            .build();
                    AuthenticationAPI authenticationAPI = new AuthenticationAPI(config);
                    authenticationAPI.deauthorize()
                            .execute();
above is my code, i try to implement deauthorize base on what you do in test module

**Comment by truizlop** [comment]
I'm sorry, could you describe the error or misbehavior you are experimenting? What is your expected result? What is the actual outcome? Which steps are you following?

**Comment by truizlop** [comment]
Also, make sure you are using the proper library version. Last version published is 1.3.

**Comment by StevenStarz** [comment]
i want to create 2 button with action connect to strava and disconnect to strava, for now connect to   strava is working, but i'm still figure out how to disconnect from strava, and i see on strava documentation http://developers.strava.com/docs/authentication/ there is deauthorize, but i can't find the deauthorize implementation on you source code

**Comment by StevenStarz** [comment]
@truizlop okay i see the function now, after i update the version

**Comment by StevenStarz** [comment]
@truizlop Thanks for your help

**Comment by StevenStarz** [comment]
@truizlop  do i need to provide code or access token, when calling deauthorize? (Because it always throw StravaUnauthorizedException)

**Comment by truizlop** [comment]
You always need to provide a valid config object. If it is throwing that exception, it may be because you are already deauthorized.

**Comment by StevenStarz** [comment]
@truizlop i already trying to reauthorize and using the token ensure is connected to strava, but i'm still got the same issue

**Comment by StevenStarz** [comment]
@truizlop

**Comment by truizlop** [comment]
With the information you are providing, there's little I can do to help. You need to check the debug logs to see what is going on. Check that you are able to use other parts of the library and check that this is actually a problem with StravaZpot before posting an issue here.

**Comment by StevenStarz** [comment]
@truizlop is working now, but i'm not using the function that you provided, I create my own request, then set the authorization header with access token, and it's working now
