### ISSUE TITLE
What to put in redirect uri and CODE

### ISSUE THREAD

**Issue by AlexKolydas** [SweetzpotAS/StravaZpot-Android#21]
Hello.I would like you to help me with the redirect uri.I put the same url that i put in the domain callback in stravas page(which is localhost). but i get this error.Can you please help by telling me which url to put?Also the  **.withCode(CODE)** what should i write?Sorry for this but i'm totally new 

<img width="960" alt="untitled" src="https://user-images.githubusercontent.com/37380835/47289294-47539380-d5fa-11e8-8726-714495971fc9.png">

**Comment by truizlop** [comment]
It would be helpful if you write the code you are using right now, otherwise the only thing I can do is refer you to the documentation, where everything is clearly explained, including the question you are asking about the `withCode(CODE)` method.

**Comment by AlexKolydas** [comment]
```
 private void login() {
        Intent intent = StravaLogin.withContext(this)
                                    .withClientID(29519)
                                    .withRedirectURI("strava.com")
                                    .withApprovalPrompt(AUTO)
                                    .withAccessScope(AccessScope.VIEW_PRIVATE_WRITE)
                                    .makeIntent();
        startActivityForResult(intent, RQ_LOGIN);
    }

    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);

        if(requestCode == RQ_LOGIN && resultCode == RESULT_OK && data != null) {
            Log.d("Strava code", data.getStringExtra(RESULT_CODE));
            AuthenticationConfig config = AuthenticationConfig.create()
                    .debug()
                    .build();
            AuthenticationAPI api = new AuthenticationAPI(config);
            LoginResult result = api.getTokenForApp(AppCredentials.with(29519, "8d55af50a97a9f4b5269670de00bf5e6f4b9942d "))
                    .withCode(RESULT_CODE)
                    .execute();
        }
    }

This is the code i haven't changed anything i believe
```

**Comment by AlexKolydas** [comment]
I haven't changed any of your code.I just want to understand what to put in
the redirecturi and CODE

**Comment by truizlop** [comment]
Referring to the documentation in the README:
- *`<YOUR_REDIRECT_URL>` must be in the domain you specified when you registered your app in Strava*. Of course, `strava.com` isn't most likely your domain for the redirect URI.
- *Notice that in this call you must provide the Client ID and Secret provided by Strava when you registered your application, and the code obtained during the login process*. A few lines above, you can see how to obtain the code:

```java
@Override
protected void onActivityResult(int requestCode, int resultCode, Intent data) {
    super.onActivityResult(requestCode, resultCode, data);

    if(requestCode == RQ_LOGIN && resultCode == RESULT_OK && data != null) {
        String code = data.getStringExtra(StravaLoginActivity.RESULT_CODE);
        // Use code to obtain token
    }
}
```

In any case, you also have an example folder [here](https://github.com/SweetzpotAS/StravaZpot-Android/blob/master/app/src/main/java/com/sweetzpot/stravazpotsample/MainActivity.java).

**Comment by AlexKolydas** [comment]
i think i manage to do something!Thank you very much!
