### ISSUE TITLE
Endless loop after "Cancel" click in Auth Page of Strava

### ISSUE THREAD

**Issue by dgngulcan** [SweetzpotAS/StravaZpot-Android#4]
Webview enters an endless loop with a progressBar after clicking "cancel" for authorization in the auth webpage of Strava

**Comment by truizlop** [comment]
Could you verify if this is an issue of the library or something related to Strava's website? If it is something with the library, please, provide detailed steps on how to reproduce the issue, with code if necessary.

**Comment by dgngulcan** [comment]
After starting `StravaLoginActivity` with my credentials, It opens a `WebView` with Strava's authorization web page that asks for my permission for my app.
When I click "authorize", I am able to get the code at `onActivityResult` as expected.
When I click "cancel", It redirects to another page with just a `progressBar`

What I suspect is that the redirected URL is not caught in [StravaLoginActivity](https://github.com/SweetzpotAS/StravaZpot-Android/blob/master/lib/src/main/java/com/sweetzpot/stravazpot/authenticaton/ui/StravaLoginActivity.java)'s
```
..
private boolean handleUrl(Uri uri) {
                String redirectURL = getIntent().getStringExtra(EXTRA_REDIRECT_URL);
                if(uri.toString().startsWith(redirectURL)) {
                    String code = uri.getQueryParameter("code");
                    return makeResult(code);
                }
                return false;
            }
..
```

Nowadays I'm pretty busy with work and side projects. I may fork and fix your awesome library when I can find time if you are busy too!

**Comment by truizlop** [comment]
Thansk @dgngulcan, I will investigate the issue and publish an update as soon as possible. I'm glad that you like the library and using it 😄

**Comment by truizlop** [comment]
Version 1.1.2 has been published solving this issue. Please, verify that it is solved and close the issue if so. Thanks for your collaboration!

**Comment by dgngulcan** [comment]
All good! Thank you too! :)
The app that I am going to use your library is [Paxira](https://play.google.com/store/apps/details?id=life.paxira.app)
If you cycle too, would like to get your critique on that!

**Comment by truizlop** [comment]
We'll take a look at it! Thanks!
