### ISSUE TITLE
Error at Sign in with Google

### ISSUE THREAD

**Issue by danieltigse** [SweetzpotAS/StravaZpot-Android#7]
This is the error

![screenshot_20170625-215732](https://user-images.githubusercontent.com/1870723/27523237-8cce7488-59f1-11e7-9aa3-0cef45ee591d.png)

**Comment by beddfaf916** [comment]
+1, but that login feature in GarminConnect app is as usual

**Comment by truizlop** [comment]
Could you provide more details about how to reproduce the error? Code that you are using to launch the login intent, steps that you are following... It would help to verify if this is an issue with our library or there is something missing in our integration with Strava. Also, pull requests with fixes are welcome.

**Comment by danieltigse** [comment]
I am using the version 1.1.3 of the library

I am launching the intent with this code:
```java
Intent intent = StravaLogin.withContext(this)
                .withClientID(XXXXX)
                .withRedirectURI("stam://stamapp.com")
                .withApprovalPrompt(ApprovalPrompt.AUTO)
                .withAccessScope(AccessScope.VIEW_PRIVATE_WRITE)
                .makeIntent();
        startActivityForResult(intent, RQ_LOGIN);
```

I have done some research and I found this, I don't know If you can fix it:

https://github.com/RocketChat/Rocket.Chat.Cordova/issues/159
https://blog.cloudrail.com/solving-disallowed_useragent-for-google-services/

**Comment by danieltigse** [comment]
Version 1.1.4 works for me. Thanks you all!

**Comment by truizlop** [comment]
Thank you for using our library!
