### ISSUE TITLE
Segment.getMap does not have polyline field.

### ISSUE THREAD

**Issue by inv2004** [SweetzpotAS/StravaZpot-Android#9]
Hello,
Was trying to use your library to retrieve favorite segments with their polylines, but...

I have the following response and You can find that map does not have summary_polyline, but just polyline (strava names it full polyline). But, unfortunately Map class do not parse this field.

Question: is it possible to add it?

`{"id":3579232,"resource_state":3,"name":"Martha's Chapel - East","activity_type":"Ride","distance":4316.06,"average_grade":0.6,"maximum_grade":3.8,"elevation_high":97.6,"elevation_low":71.2,"start_latlng":[35.78940027393401,-79.00851692073047],"end_latlng":[35.790341310203075,-78.96480194292963],"start_latitude":35.78940027393401,"start_longitude":-79.00851692073047,"end_latitude":35.790341310203075,"end_longitude":-78.96480194292963,"climb_category":0,"city":"Apex","state":"NC","country":"United States","private":false,"hazardous":false,"starred":true,"created_at":"2013-03-09T20:31:02Z","updated_at":"2017-07-23T08:05:38Z","total_elevation_gain":36.2302,"map":{"id":"s3579232","polyline":"wbmyEfjfaN@kLGqM@eEDcCAiKLoQA_B@aEE_BQgBMw@_@mBy@_CoA_DyBcG[q@u@wA}@cCa@oAWi@k@aB]w@uAuEkE}MaAcCw@gCcAsDsAsFa@oCU{DA{CBiDLqGDs@Fs@Js@ZgBb@aBp@qBd@s@vBeCxEcFzCoDx@mAt@yAfByDh@_B\\aBRaBDq@DaB@aEB}CH{C?eB","resource_state":3},"effort_count":24497,"athlete_count":2098,"star_count":16,"athlete_segment_stats":{"pr_elapsed_time":368,"pr_date":"2017-07-13","effort_count":15}}`

Thank you,

**Comment by inv2004** [comment]
You can find more detailed information I found about polyline and summary_polyline here: https://github.com/jaredholdcroft/strava-api-v3/issues/11#issuecomment-212579573

**Comment by truizlop** [comment]
StravaZpot 1.2 has been sent to JCenter with a new field `polyline` in `Map`. Please, update your dependencies and check if that works for you. Make sure you select `getPolyline()` instead of `getSummaryPolyline()`. The issue is Strava sometimes fills the summary field, and some others fill the polyline field.

**Comment by inv2004** [comment]
It works. Thank you!

**Comment by truizlop** [comment]
Thank you for using our library!
